---
title: Ongoing research
---

## Innovation and Motherhood



<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5527321" target="_blank"> Working Paper</a> 

“Innovation and Motherhood” (2025, with __Clemens Müller__ and __Stefan Obernberger__), <br>  _Available at SSRN_ 

We investigate the impact of childbirth on the careers of women in innovation, a male dominated field. We find that the fertility rate of female inventors is remarkably low. Most female inventors have their first child only after filing their first patent application. Following birth, female inventors are much less likely to file patents. Much of the loss in patent output can be explained by temporary (maternity) leave, part-time work, and lower mobility. The innovation gap after childbirth leads to economically meaningful wage disparities, indicating a substantial depreciation of female inventors' human capital. Male inventors also face declines in their innovation output and earnings, but these losses are much smaller than those observed for women. Our findings emphasize the difficulties of reconciling a career in innovation with being a parent in general and with being a mother in particular. 

## Changing Fertility and Heterogeneous Motherhood Effects: <br> Revisiting the Effects of a Parental Benefits Reform 

<a href="https://www.iza.org/publications/dp/16966/changing-fertility-and-heterogeneous-motherhood-effects-revisiting-the-effects-of-a-parental-benefits-reform" target="_blank"> Working Paper</a> 

“Changing Fertility and Heterogeneous Motherhood Effects: Revisiting the Effects of a Parental Benefits Reform” (2024, with __Bernd Fitzenberger__), _IZA Discussion Paper No. 16966_ <br>
R&R at _Journal of Labor Economics_

Using a semiparametric event study approach with a control group, we estimate the effect of motherhood on labor market outcomes in Germany, the child penalty. We further investigate how the 2007 parental benefits reform changed the child penalty while accounting for fertility effects. A large novel data set linking data from two administrative sources provides information on all births. Our estimation approach accounts for motherhood being a staggered treatment. The reform has small positive medium-run effects employment outcomes. It changes the selection into fertility and shows heterogeneous effects. However, the reform did little to reduce the average child penalty.



