---
title: Policy Paper
---

## Ganztag in der Grundschule: Vorteile für Kinder sichtbar



<a href="https://www.ifo.de/publikationen/2025/aufsatz-zeitschrift/ganztag-der-grundschule-vorteile-fuer-kinder-sichtbar"> Article  </a> 

“Ganztag in der Grundschule: Vorteile für Kinder sichtbar” <br> (2025, with __Larissa Zierow__), _ifo Schnelldienst, 2025, 78, Nr. 10 64-68_ 

Ganztagskonzepte in der Grundschule haben in den letzten zwei Jahrzehnten stark an Bedeutung gewonnen. Eine aktuelle Studie zeigt, dass die Förderung des Bundes für den Ausbau von Ganztagsplätzen die Teilnahmequote deutlich erhöht hat und für Kinder spürbare Vorteile mit sich bringt. So verbessern sich die Deutschnoten und die Wahrscheinlichkeit, nach der Grundschule das Gymnasium zu besuchen. Zudem steigert sich durch den Ganztag die Zufriedenheit mit ihrer Schule und sie sind seltener Mobbing ausgesetzt. Auf die standardisierten Testergebnisse in Deutsch und Mathematik zeigen sich dagegen keine eindeutigen Effekte. Hinsichtlich des Ziels, Bildungsungleichheiten zu verringern, liefern die Daten keine Hinweise auf einen großen Effekt der Ganztagsschulen.


## In familienfreundlichen Betrieben nehmen Väter häufiger Elternzeit in Anspruch



<a href="https://iab-forum.de/in-familienfreundlichen-betrieben-nehmen-vaeter-haeufiger-elternzeit-in-anspruch/"> Article  </a> 

“In familienfreundlichen Betrieben nehmen Väter häufiger Elternzeit in Anspruch” <br> (2025, with __Ann-Christin Bächmann__ and __Corinna Frodermann__), _IAB-Forum 28. Juli 2025_ 

Daten des IAB zeigen: Die Entscheidung von Vätern, in Elternzeit zu gehen, hängt stark vom Betrieb ab, in dem sie tätig sind. So ist der Anteil verheirateter Väter, die Elternzeit in Anspruch nehmen, in Betrieben mit familienfreundlichen Maßnahmen höher als in solchen ohne entsprechende Angebote. Dieser Zusammenhang bleibt auch dann bestehen, wenn weitere betriebliche und persönliche Merkmale berücksichtigt werden.


## Neues zur Lohnungleichheit in Deutschland



<a href="https://www.ifo.de/publikationen/2020/aufsatz-zeitschrift/ungleichheit-unter-der-lupe-neue-politische-antworten-auf"> Article  </a> 

“Neues zur Lohnungleichheit in Deutschland” (2020, with __Mario Bossler__ and __Bernd Fitzenberger__),<br> _ifo-Schnelldienst 02/2020_ 

Die Lohnungleichheit unter Vollzeitbeschäftigten in
Westdeutschland ist zwischen 1990 und 2010 stark
angestiegen, wobei die Reallöhne im unteren Bereich
der Lohnverteilung deutlich gefallen sind. Neuere
Befunde zeigen, dass neben anderen in der Literatur
diskutierten Faktoren die zunehmende Heterogenität der Erwerbsverläufe einen Teil des Anstiegs der
Lohnungleichheit erklären kann. Seit 2011 ist dahingehend eine Trendwende zu erkennen, dass die Löhne
der Vollzeitbeschäftigten in Westdeutschland entlang
der gesamten Lohnverteilung gestiegen sind und die
Lohnungleichheit nicht mehr weiter zugenommen
hat. Mit der Einführung des gesetzlichen Mindestlohns
im Jahr 2015 erhöht sich das 10%-Quantil der gesamtdeutschen Lohnverteilung, was mit einem Rückgang
der Lohnungleichheit am unteren Ende der Lohnverteilung – vor allem in Ostdeutschland – einhergeht.


